language: node_js
node_js:
  - '0.10'
  - '0.11'
env:
  global:
    - NODE_ENV=travisci
    - BUILD_DIR=`pwd`/kariudo
before_script:
  - npm install -g bower grunt-cli
  - bower install
services: mongodb
